services:
  postgres:
    image: postgres
    # restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      
  redis:
    image: redis
    container_name: local-redis
    ports:
      - "6379:6379"
